### ISSUE TITLE
Logging out shows last notification

### ISSUE THREAD

**Issue by armandasalmd** [armandasalmd/notex-client#10]
Logging out shows last notification which is incorrect. Find out why it was not cleared from state correctly

**Comment by anikashc** [comment]
can you point out to the file which has the logout action and its corresponding reducer

**Comment by armandasalmd** [comment]
@anikashc Yes, I can give you more details. I am using antd UI library. In this case I want to use this component: https://ant.design/components/message/
![image](https://user-images.githubusercontent.com/17089888/110524489-5ffd6f00-810b-11eb-9410-eab6223e04e3.png)

Problem is that I want to raise antd message from action functions. For example if action login failed, then I dispatch pushMessage action from https://github.com/armandasalmd/notex-client/blob/master/src/actions/messageActions.js

This updates messageReducer state here: https://github.com/armandasalmd/notex-client/blob/master/src/reducers/messageReducer.js

```js
const initialState = {
    messageIdCounter: 0,
    messageQueue: []
};
```

Finally, there is Message react component (which is bound to App component but returns null)
https://github.com/armandasalmd/notex-client/blob/master/src/components/components/Message.jsx

Message component subscribes to state.message and displays antd notification when detects messages in messageQueue.
After then it pops a message from queue

**Comment by armandasalmd** [comment]
This is quite complex solution. Maybe it's worth considering to rewrite this logic. We could try creating utilities/message.js

then import { message } from 'antd';

and do it for info, success, warning, error. I didnt try this, maybe it would work

Problem is that I dont want to use **import { message } from 'antd';** in redux action files because it belongs to .jsx files. But having a centralised utilities file to control that would be ok

@anikashc

**Comment by armandasalmd** [comment]
If you cannot reproduce the bug, I can show you how

**Comment by anikashc** [comment]
Why are you using a queue for the messages? Like if I want to login, I can dispatch my login action and get the  success, error states from the reducer. I would still like you to show me what the error is. After that we can start debugging the existing process only.

**Comment by armandasalmd** [comment]
This was a solution I came up originally, thats why. Can you suggest something better?

**Comment by anikashc** [comment]
> Like if I want to login, I can dispatch my login action and get the success, error states from the reducer.

This can be done. I suggest to employ useDispatch function from react-redux for error, success, loading messages.  If you want, we can give it a try.

**Comment by armandasalmd** [comment]
@anikashc go for it. You can fork this repo. Let me know if you need my help. Do you have any social media? Discord?

**Comment by armandasalmd** [comment]
Notification message refactoring complete. Related issue fixed as well: https://github.com/armandasalmd/notex-client/issues/20

Fix will come out with next release
